# API endpoint configurations for the options trading engine

tradier:
  base_url: "https://api.tradier.com"
  sandbox_url: "https://sandbox.tradier.com"
  endpoints:
    market_data:
      quotes: "/v1/markets/quotes"
      options_chains: "/v1/markets/options/chains"
      options_strikes: "/v1/markets/options/strikes"
      options_expirations: "/v1/markets/options/expirations"
      market_calendar: "/v1/markets/calendar"
      clock: "/v1/markets/clock"
      search: "/v1/markets/search"
      timesales: "/v1/markets/timesales"
      etb: "/v1/markets/etb"
    fundamentals:
      company: "/v1/markets/fundamentals/company"
      corporate_calendars: "/v1/markets/fundamentals/calendars"
      dividends: "/v1/markets/fundamentals/dividends"
      corporate_actions: "/v1/markets/fundamentals/corporate_actions"
      ratios: "/v1/markets/fundamentals/ratios"
      statistics: "/v1/markets/fundamentals/statistics"
    historical:
      history: "/v1/markets/history"
    accounts:
      profile: "/v1/user/profile"
      balances: "/v1/accounts/{account_id}/balances"
      positions: "/v1/accounts/{account_id}/positions"
      history: "/v1/accounts/{account_id}/history"
      gainloss: "/v1/accounts/{account_id}/gainloss"
      orders: "/v1/accounts/{account_id}/orders"
    trading:
      place_order: "/v1/accounts/{account_id}/orders"
      modify_order: "/v1/accounts/{account_id}/orders/{order_id}"
      cancel_order: "/v1/accounts/{account_id}/orders/{order_id}"
  rate_limits:
    requests_per_minute: 120
    burst_size: 5
  timeout: 30

yahoo:
  base_url: "https://query1.finance.yahoo.com"
  endpoints:
    market_data:
      quote: "/v8/finance/chart/{symbol}"
      quotes: "/v7/finance/quote"
      options: "/v7/finance/options/{symbol}"
      spark: "/v7/finance/spark"
      download: "/v7/finance/download/{symbol}"
    fundamentals:
      financials: "/v10/finance/quoteSummary/{symbol}"
      earnings: "/v10/finance/quoteSummary/{symbol}"
      analysis: "/v10/finance/quoteSummary/{symbol}"
      statistics: "/v10/finance/quoteSummary/{symbol}"
    news:
      news: "/v1/finance/search"
      trending: "/v1/finance/trending/{region}"
  rate_limits:
    requests_per_minute: 2000
    burst_size: 10
  timeout: 30

fred:
  base_url: "https://api.stlouisfed.org"
  endpoints:
    economic_data:
      series: "/fred/series"
      series_observations: "/fred/series/observations"
      series_search: "/fred/series/search"
      series_categories: "/fred/series/categories"
      categories: "/fred/category"
      category_series: "/fred/category/series"
      category_children: "/fred/category/children"
      releases: "/fred/releases"
      release_series: "/fred/release/series"
      release_dates: "/fred/release/dates"
      sources: "/fred/sources"
      tags: "/fred/tags"
      related_tags: "/fred/related_tags"
      tag_series: "/fred/tags/series"
  rate_limits:
    requests_per_minute: 120
    burst_size: 5
  timeout: 30

quiver:
  base_url: "https://api.quiverquant.com"
  endpoints:
    government:
      congress_trading: "/beta/live/congresstrading"
      senate_trading: "/beta/live/senatetrading"
      house_trading: "/beta/live/housetrading"
      lobbying: "/beta/live/lobbying"
      contracts: "/beta/live/govcontracts"
    social:
      reddit: "/beta/live/reddit"
      twitter: "/beta/live/twitter"
      stocktwits: "/beta/live/stocktwits"
      wsb: "/beta/live/wallstreetbets"
    institutional:
      insider_trading: "/beta/live/insidertrading"
      institutional_holdings: "/beta/live/institutionalholdings"
      fails_to_deliver: "/beta/live/ftd"
      short_interest: "/beta/live/shortinterest"
      beta_live: "/beta/live/beta"
    flow:
      flow: "/beta/live/flow"
      darkpool: "/beta/live/darkpool"
      gamma: "/beta/live/gamma"
      off_exchange: "/beta/live/offexchange"
  rate_limits:
    requests_per_minute: 300
    burst_size: 10
  timeout: 30

# Custom endpoints for additional data sources
custom:
  cboe:
    base_url: "https://cdn.cboe.com"
    endpoints:
      vix: "/api/global/delayed_quotes/VIX"
      put_call_ratio: "/api/global/delayed_quotes/CPCE"
      skew: "/api/global/delayed_quotes/SKEW"
    rate_limits:
      requests_per_minute: 60
      burst_size: 3
    timeout: 30

  treasury:
    base_url: "https://api.fiscaldata.treasury.gov"
    endpoints:
      daily_treasury_rates: "/services/api/v1/accounting/od/avg_interest_rates"
      treasury_auctions: "/services/api/v1/accounting/od/auctions_query"
    rate_limits:
      requests_per_minute: 1000
      burst_size: 10
    timeout: 30

  economic_calendar:
    base_url: "https://api.marketwatch.com"
    endpoints:
      calendar: "/investing/economic-calendar"
      earnings: "/investing/earnings-calendar"
    rate_limits:
      requests_per_minute: 60
      burst_size: 5
    timeout: 30

# Error handling configurations
error_handling:
  max_retries: 3
  retry_delay: 1.0
  backoff_factor: 2.0
  timeout_multiplier: 1.5
  circuit_breaker:
    failure_threshold: 5
    recovery_timeout: 300
    expected_exception_types:
      - "requests.exceptions.ConnectionError"
      - "requests.exceptions.Timeout"
      - "requests.exceptions.HTTPError"

# Request configurations
request_configs:
  headers:
    tradier:
      Accept: "application/json"
      Authorization: "Bearer {token}"
    yahoo:
      Accept: "application/json"
      User-Agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36"
    fred:
      Accept: "application/json"
      api_key: "{api_key}"
    quiver:
      Accept: "application/json"
      X-CSRFToken: "{csrf_token}"
      Authorization: "Token {token}"
  
  query_params:
    fred:
      file_type: "json"
      api_key: "{api_key}"
    yahoo:
      format: "json"
      lang: "en-US"
      region: "US"
    tradier:
      greeks: "true"
      
# Data validation rules
validation:
  quote_age_threshold: 600  # 10 minutes in seconds
  price_change_threshold: 0.20  # 20% price change threshold
  volume_threshold: 10000  # Minimum volume threshold
  market_hours:
    premarket_start: "04:00"
    market_open: "09:30"
    market_close: "16:00"
    afterhours_end: "20:00"
    timezone: "America/New_York"