# Options Trading Engine Configuration
# Complete configuration with all parameters from project requirements

# Application Settings
application:
  name: "Options Trading Engine"
  version: "1.0.0"
  environment: "production"
  debug: false
  log_level: "INFO"

# Execution Settings
execution:
  interval_minutes: 15
  market_hours_only: true
  max_concurrent_trades: 10
  max_portfolio_allocation: 0.05  # 5% max per position
  emergency_stop_enabled: true

# Database Configuration
database:
  host: "localhost"
  port: 5432
  database: "options_engine"
  user: "options_engine_user"
  password: "${DATABASE_PASSWORD}"
  pool_size: 20
  max_overflow: 30
  pool_timeout: 30
  pool_recycle: 3600

# Cache Configuration
cache:
  redis_host: "localhost"
  redis_port: 6379
  redis_db: 0
  redis_password: "${REDIS_PASSWORD}"
  default_ttl: 300  # 5 minutes
  max_memory: "256mb"
  eviction_policy: "allkeys-lru"

# API Configuration
api:
  tradier:
    base_url: "https://api.tradier.com/v1/"
    rate_limit: 120  # requests per minute
    timeout: 30
    retries: 3
    backoff_factor: 2
  
  yahoo_finance:
    base_url: "https://query1.finance.yahoo.com/"
    rate_limit: 2000  # requests per hour
    timeout: 30
    retries: 3
    backoff_factor: 1.5
  
  fred:
    base_url: "https://api.stlouisfed.org/fred/series/observations"
    rate_limit: 120  # requests per minute
    timeout: 30
    retries: 3
    backoff_factor: 2
  
  quiver:
    base_url: "https://api.quiverquant.com/"
    rate_limit: 300  # requests per minute
    timeout: 30
    retries: 3
    backoff_factor: 2

# Trading Parameters
trading:
  # Portfolio Settings
  nav: 100000  # Net Asset Value
  available_capital: 5000  # Available trading capital
  max_portfolio_allocation: 0.05  # 5% max per position
  
  # Strategy Settings
  strategies:
    - "PUT_CREDIT_SPREAD"
    - "CALL_CREDIT_SPREAD"
    - "IRON_CONDOR"
    - "COVERED_CALL"
    - "CASH_SECURED_PUT"
  
  # Default watchlist
  watchlist:
    - "AAPL"
    - "MSFT"
    - "GOOGL"
    - "TSLA"
    - "NVDA"
    - "AMZN"
    - "META"
    - "NFLX"
    - "SPY"
    - "QQQ"

# Hard Constraints
constraints:
  hard:
    # Probability of Profit
    min_pop: 0.65
    
    # Credit Requirements
    min_credit_ratio: 0.33
    
    # Days to Expiration
    min_dte: 15
    max_dte: 45
    
    # Liquidity Requirements
    min_volume: 10
    min_open_interest: 50
    max_bid_ask_spread: 0.50
    
    # Sector Diversification
    max_sector_allocation: 0.40
    
    # Portfolio Limits
    max_total_theta: -200
    max_total_vega: 1000
    max_total_delta: 500
    max_net_liquidity: 50000
    
    # Options Constraints
    max_delta_long: 0.70
    max_delta_short: -0.30
    min_iv_rank: 30
    max_iv_rank: 90
    
    # Earnings Filters
    min_days_to_earnings: 7
    
    # Technical Filters
    max_rsi: 70
    min_rsi: 30
    momentum_z_threshold: 2.0
    flow_z_threshold: 2.0

# Scoring Weights
scoring:
  weights:
    pop: 0.25
    iv_rank: 0.20
    momentum: 0.20
    flow: 0.15
    risk_reward: 0.15
    liquidity: 0.05
  
  # Market Regime Adjustments
  regime_adjustments:
    high_volatility:
      pop: 0.30
      iv_rank: 0.15
      momentum: 0.15
      flow: 0.15
      risk_reward: 0.20
      liquidity: 0.05
    
    low_volatility:
      pop: 0.20
      iv_rank: 0.25
      momentum: 0.25
      flow: 0.15
      risk_reward: 0.10
      liquidity: 0.05

# Performance Settings
performance:
  thread_pool_size: 8
  max_workers: 32
  batch_size: 100
  parallel_processing: true
  memory_limit: "2gb"
  cpu_limit: 80  # percentage
  optimization_level: "balanced"  # conservative, balanced, aggressive

# Monitoring Configuration
monitoring:
  enabled: true
  interval: 60  # seconds
  metrics_port: 8080
  health_check_enabled: true
  
  # Thresholds
  thresholds:
    cpu_usage_warning: 70
    cpu_usage_critical: 90
    memory_usage_warning: 80
    memory_usage_critical: 95
    disk_usage_warning: 85
    disk_usage_critical: 95
    api_response_time_warning: 5.0
    api_response_time_critical: 10.0
    error_rate_warning: 5.0
    error_rate_critical: 10.0

# Alert Configuration
alerts:
  email:
    enabled: true
    smtp_server: "smtp.gmail.com"
    smtp_port: 587
    use_tls: true
    from_email: "alerts@yourcompany.com"
    to_emails:
      - "admin@yourcompany.com"
      - "ops@yourcompany.com"
    username: "${SMTP_USERNAME}"
    password: "${SMTP_PASSWORD}"
  
  slack:
    enabled: true
    webhook_url: "${SLACK_WEBHOOK_URL}"
    channel: "#options-engine-alerts"
    username: "Options Engine Bot"

# Logging Configuration
logging:
  level: "INFO"
  format: "%(asctime)s [%(levelname)s] %(name)s: %(message)s"
  file: "logs/options_engine.log"
  max_size: "10MB"
  backup_count: 5
  rotation: "daily"

# Error Handling
error_handling:
  max_retries: 3
  retry_delay: 1  # seconds
  exponential_backoff: true
  circuit_breaker_enabled: true
  circuit_breaker_threshold: 5
  circuit_breaker_timeout: 60
  graceful_degradation: true

# Data Quality
data_quality:
  min_data_freshness: 600  # 10 minutes
  max_missing_data_ratio: 0.1  # 10%
  data_validation_enabled: true
  outlier_detection_enabled: true
  data_consistency_checks: true

# Backtesting Configuration
backtesting:
  enabled: true
  start_date: "2022-01-01"
  end_date: "2023-12-31"
  initial_capital: 100000
  commission_per_contract: 0.50
  slippage_factor: 0.001
  walk_forward_analysis: true
  out_of_sample_ratio: 0.2

# Risk Management
risk_management:
  max_drawdown: 0.10  # 10%
  max_correlation: 0.70
  stress_testing_enabled: true
  var_confidence_level: 0.95
  expected_shortfall_enabled: true
  dynamic_hedging_enabled: true

# Security Settings
security:
  ssl_enabled: true
  api_key_rotation_enabled: true
  data_encryption_enabled: true
  audit_logging_enabled: true
  access_control_enabled: true

# Development Settings
development:
  debug_mode: false
  test_mode: false
  mock_api_enabled: false
  profiling_enabled: false
  verbose_logging: false